---
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0f88e80871fd81e91
      InstanceType: t3.micro
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          echo "|| Downloading user data..."
          aws s3 cp s3://s3-og/main.sh main.sh

          echo "|| Running user data..."
          chmod +x ./main.sh
          ./main.sh
